name = "CTFlows"
uuid = "1c39547c-7794-42f7-af83-d98194f657c2"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]
version = "0.8.10-beta"

[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
CTModels = "34c4fa32-2049-4079-8329-de33c2a22e2d"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[weakdeps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[extensions]
CTFlowsODE = "OrdinaryDiffEq"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CTParser = "32681960-a1b1-40db-9bff-a1ca817385d1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "CTParser", "OrdinaryDiffEq", "Plots", "Test"]

[compat]
Aqua = "0.8"
CTBase = "0.16, 0.17"
CTModels = "0.6"
CTParser = "0.7"
DocStringExtensions = "0.9"
ForwardDiff = "0.10, 1.0"
LinearAlgebra = "1"
MLStyle = "0.4"
MacroTools = "0.5"
OrdinaryDiffEq = "6"
Plots = "1"
Test = "1"
julia = "1.10"